[package]
name = "bitwarden-sync"
version = "0.1.0"
authors = ["kjcodeacct <kjcodeacct@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.27.0"
dialoguer = "~0.5.0"